### ISSUE TITLE
 tuner script issues when applying mod to `musicutil.note_num_to_freq`

### ISSUE THREAD

**Issue by pq** [catfact/z_tuning#3]
Initially reported on lines (https://llllllll.co/t/tuner/21088/12) and I just hit this so I figured I'd grab a stack trace while it was handy.

```
/home/we/dust/code/z_tuning/lib/tuning.lua:25: attempt to perform arithmetic on a nil value (global 'deg')
stack traceback:
	/home/we/dust/code/z_tuning/lib/tuning.lua:25: in function </home/we/dust/code/z_tuning/lib/tuning.lua:3>
	(...tail calls...)
	/home/we/dust/code/z_tuning/lib/mod.lua:161: in function 'musicutil.note_num_to_freq'
	/home/we/dust/code/tuner/tuner.lua:125: in function 'core/script.redraw'
	/home/we/dust/code/tuner/tuner.lua:90: in field 'event'
	/home/we/norns/lua/core/metro.lua:164: in function </home/we/norns/lua/core/metro.lua:160>
```

The repro is easy. Just load the [tuner script](https://llllllll.co/t/tuner/21088/) and set a `Z_TUNING` in the `SYSTEM` menu.

**Comment by catfact** [comment]
not sure how it stayed in but there is what looks like a typo. i pushed a blind fix to main, and will test it later or tomorrow or something.

**Comment by pq** [comment]
thanks for taking a look!

I know you said it was untested but I couldn't resist and for kicks, I patched that in and got a little further:

```
/home/we/dust/code/z_tuning/lib/tuning.lua:27: attempt to perform arithmetic on a nil value (field '?')
stack traceback:
	/home/we/dust/code/z_tuning/lib/tuning.lua:27: in function </home/we/dust/code/z_tuning/lib/tuning.lua:3>
	(...tail calls...)
	/home/we/dust/code/z_tuning/lib/mod.lua:161: in function 'musicutil.note_num_to_freq'
	/home/we/dust/code/octaves/tuner.lua:158: in function 'redraw'
	/home/we/dust/code/octaves/tuner.lua:123: in field 'event'
	/home/we/norns/lua/core/metro.lua:164: in function </home/we/norns/lua/core/metro.lua:160>
```

took a quick glance and nothing obvious jumped out at me... (fwiw: trying `mt_quarter_comma`)

anyway, again thanks!

**Comment by catfact** [comment]
yeeep, i had some local changes on one norns that somehow never made it to git. apologies!

i pushed changes and v0.2.1 tag. 

seems to work and i tested the function output and looks ok.

i should say... though the `tuner` script will not crash now, it won't quite work correctly either when "cents" are interpreted to mean "log-spaced frequency points between arbitrary note frequencies." 

one issue being that `z_tuning` doesn't attempt to match the inverse function `freq_to_note_num` to the presently defined `note_num_to_freq`. (the reason is that it's mathematically impossible to do so in the general sense, but if i make a v.0.3.0 i will attempt to solve that for table-based tunings at least.)

(i also have some WIP slowly going for adding MTS output and supporting scala keymap files.)
